services:

  warehouse-service:
    image: quarkus/warehouse-service-jvm
    depends_on:
      - postgres
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/warehouse_db
      QUARKUS_DATASOURCE_USERNAME: admin
      QUARKUS_DATASOURCE_PASSWORD: admin
    ports:
      - 8080:8080
    networks:
      - warehouse_network

  order-service:
    image: quarkus/order-service-jvm
    depends_on:
      - postgres
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/warehouse_db
      QUARKUS_DATASOURCE_USERNAME: admin
      QUARKUS_DATASOURCE_PASSWORD: admin
    ports:
      - 8081:8081
    networks:
      - warehouse_network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: warehouse_db
    networks:
      - warehouse_network

networks:
  warehouse_network:
    driver: bridge